### ISSUE TITLE
[Install error] undeclared identifier: 'readFasta'

### ISSUE THREAD

**Issue by Yasin-Zhao** [Benjamin-Lee/vdsearch#9]
Hi, there was an error according to your Installation tutorial. I guess it was due to the bioseq package, and where to get the correct package?
![未命名图片](https://user-images.githubusercontent.com/25842186/219243417-68267442-d90e-4b4f-abe7-64cce1472a23.png)

**Comment by Benjamin-Lee** [comment]
Thanks for the report! I was able to supply the missing library in d2368a36c73eafc94eb40fdfecffc7af3d29e51d, so this error should be resolved now.
